// This file generated by ngrestcg
// For more information, please visit: https://github.com/loentar/ngrest

#ifndef YB_PROOF_2018_H
#define YB_PROOF_2018_H

#include <ngrest/common/Service.h>

//! Dummy description for the service
/*! Some detailed description of the service */
// '*location' comment sets resource path for this service
// *location: yb_proof_2018
class yb_proof_2018: public ngrest::Service
{
public:
    // Here is an example of service operation
    //! Dummy description for the operation
    /*! Some detailed description of the operation */
    // To invoke this operation from browser open: http://localhost:9098/yb_proof_2018/World!
    //
    // '*location' metacomment sets path to operation relative to service operation.
    // Default value is operation name.
    // This will bind "echo" method to resource path: http://host:port/yb_proof_2018/{text}
    // *location: /{text}
    //
    // '*method' metacomment sets HTTP method for the operation. GET is default method.
    // *method: GET
    //
    std::string echo(const std::string& text)
    {
        return "Hi, " + text;
    }
};


#endif // YB_PROOF_2018_H



